[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solvote_wallet = "BK5UCcfueEnGzvWf7tnQ7izAGupynCNn8bLXHpR128vu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://localhost:8899"
wallet = "/home/reek/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
